import { Student } from './types';

export const INITIAL_MOCK_STUDENTS: Student[] = [
  {
    id: "6620901001",
    name: "นายสมชาย ใจดี",
    level: "ปวช. 1",
    department: "เทคโนโลยีสารสนเทศ",
    room: "1",
    parentName: "นายสมบูรณ์ ใจดี",
    parentPhone: "081-234-5678",
    address: "12/3 ถ.มิตรภาพ อ.เมือง จ.ขอนแก่น",
    latitude: 16.4322,
    longitude: 102.8230,
    visitStatus: "เยี่ยมแล้ว",
    visitData: {
      visitDate: "2026-06-15",
      travelInfo: "รถจักรยานยนต์ ทางเข้าเป็นซอยคอนกรีตแคบ รถยนต์เข้าได้ทางเดียว",
      latitude: 16.4322,
      longitude: 102.8230,
      houseCondition: "มั่นคงแข็งแรง",
      houseOwnership: "บ้านตนเอง",
      familyStatus: "อยู่กับบิดามารดา",
      relationshipScale: 5,
      averageMonthlyIncome: 18000,
      debtStatus: "มีหนี้สินในระบบ",
      risks: {
        academic: false,
        substance: false,
        gaming: false,
        relationship: false,
        financial: false,
        travelRisk: false
      },
      riskNotes: "ครอบครัวอบอุ่นและดูแลเอาใจใส่การเรียนของนักเรียนเป็นอย่างดี ไม่มีเรื่องน่าห่วง",
      housePhoto: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=60",
      parentPhoto: "https://images.unsplash.com/photo-1544027993-37dbfe43562a?w=600&auto=format&fit=crop&q=60",
      screeningResult: "ปกติ",
      counselorNotes: "ควรส่งเสริมด้านทุนการศึกษาเรียนดี และสนับสนุนเข้าร่วมแข่งขันทักษะวิชาการ",
      submittedBy: "ครูมาลี รักเรียน"
    }
  },
  {
    id: "6620901002",
    name: "นางสาววิภาวดี เรียนเก่ง",
    level: "ปวช. 1",
    department: "เทคโนโลยีสารสนเทศ",
    room: "1",
    parentName: "นางรุ่งเรือง เรียนเก่ง",
    parentPhone: "089-876-5432",
    address: "45 หมู่ 5 ต.ศิลา อ.เมือง จ.ขอนแก่น",
    latitude: 16.4820,
    longitude: 102.8412,
    visitStatus: "ยังไม่ได้เยี่ยม"
  },
  {
    id: "6520201005",
    name: "นายกิตติพงษ์ ยอดขยัน",
    level: "ปวช. 2",
    department: "ช่างยนต์",
    room: "2",
    parentName: "นายพงษ์ ยอดขยัน",
    parentPhone: "085-111-2222",
    address: "99/1 ต.ในเมือง อ.เมือง จ.ขอนแก่น",
    latitude: 16.4150,
    longitude: 102.8120,
    visitStatus: "เยี่ยมแล้ว",
    visitData: {
      visitDate: "2026-06-18",
      travelInfo: "รถกระบะ ติดถนนหลัก สังเกตง่ายข้างร้านซ่อมรถ",
      latitude: 16.4150,
      longitude: 102.8120,
      houseCondition: "ปานกลาง/มีจุดชำรุด",
      houseOwnership: "บ้านตนเอง",
      familyStatus: "อยู่กับบิดามารดา",
      relationshipScale: 4,
      averageMonthlyIncome: 12000,
      debtStatus: "มีทั้งในและนอกระบบ",
      risks: {
        academic: false,
        substance: false,
        gaming: false,
        relationship: false,
        financial: true,
        travelRisk: false
      },
      riskNotes: "ผู้ปกครองรายได้ไม่แน่นอนและมีหนี้นอกระบบกู้มาลงทุนร้านซ่อมรถ ทำให้นักเรียนต้องช่วยงานหลังเลิกเรียน ส่งผลให้บางวันเหนื่อยล้าในการเรียน",
      housePhoto: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=600&auto=format&fit=crop&q=60",
      parentPhoto: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=60",
      screeningResult: "เสี่ยง",
      counselorNotes: "แนะนำให้ทำเรื่องขอทุนการศึกษาช่วยเหลือผู้ขาดแคลนทุนทรัพย์ เพื่อแบ่งเบาภาระครอบครัว",
      submittedBy: "ครูสมศักดิ์ แข็งขัน"
    }
  },
  {
    id: "6420304012",
    name: "นางสาวมนัสวี แสนสุข",
    level: "ปวช. 3",
    department: "การบัญชี",
    room: "1",
    parentName: "นางดวงตา แสนสุข",
    parentPhone: "086-333-4444",
    address: "234 หมู่ 12 ต.บ้านเป็ด อ.เมือง จ.ขอนแก่น",
    latitude: 16.4385,
    longitude: 102.7845,
    visitStatus: "เยี่ยมแล้ว",
    visitData: {
      visitDate: "2026-06-20",
      travelInfo: "รถจักรยานยนต์ ซอยบ้านค่อนข้างลึกและมืดในเวลากลางคืน",
      latitude: 16.4385,
      longitude: 102.7845,
      houseCondition: "มั่นคงแข็งแรง",
      houseOwnership: "บ้านเช่า",
      familyStatus: "อยู่กับมารดา (บิดาเสียชีวิต/แยกทาง)",
      relationshipScale: 4,
      averageMonthlyIncome: 9500,
      debtStatus: "มีหนี้สินในระบบ",
      risks: {
        academic: false,
        substance: false,
        gaming: false,
        relationship: false,
        financial: true,
        travelRisk: true
      },
      riskNotes: "นักเรียนอยู่กับมารดาเพียงสองคน มารดาทำงานรับจ้างทั่วไป บ้านอยู่ในซอยลึก การเดินทางกลับบ้านในช่วงค่ำหลังเลิกกิจกรรมมีความเสี่ยง",
      housePhoto: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=600&auto=format&fit=crop&q=60",
      parentPhoto: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=600&auto=format&fit=crop&q=60",
      screeningResult: "เสี่ยง",
      counselorNotes: "แนะแนวเรื่องการจัดหางานพิเศษพาร์ทไทม์ในสถานศึกษา และช่วยเฝ้าระวังเรื่องความปลอดภัยในการเดินทางช่วงค่ำ",
      submittedBy: "ครูวิภา พันธ์งาม"
    }
  },
  {
    id: "6330901001",
    name: "นายธนกร วงศ์สมบูรณ์",
    level: "ปวส. 1",
    department: "คอมพิวเตอร์ธุรกิจ",
    room: "1",
    parentName: "นายธีรวัฒน์ วงศ์สมบูรณ์",
    parentPhone: "082-555-6666",
    address: "111 ต.โคกสี อ.เมือง จ.ขอนแก่น",
    latitude: 16.4710,
    longitude: 102.9150,
    visitStatus: "ยังไม่ได้เยี่ยม"
  },
  {
    id: "6230901024",
    name: "นางสาวอนงค์นาฏ แก้วตา",
    level: "ปวส. 2",
    department: "คอมพิวเตอร์ธุรกิจ",
    room: "2",
    parentName: "นางกานดา แก้วตา",
    parentPhone: "083-777-8888",
    address: "88/2 หมู่ 3 ต.บึงเนียม อ.เมือง จ.ขอนแก่น",
    latitude: 16.4605,
    longitude: 102.9402,
    visitStatus: "เยี่ยมแล้ว",
    visitData: {
      visitDate: "2026-06-25",
      travelInfo: "รถกระบะ ข้ามสะพานไม้เลียบคลองชลประทาน",
      latitude: 16.4605,
      longitude: 102.9402,
      houseCondition: "ทรุดโทรม/ไม่มั่นคง",
      houseOwnership: "อาศัยญาติ",
      familyStatus: "อยู่กับญาติ/ผู้ปกครอง",
      relationshipScale: 3,
      averageMonthlyIncome: 5000,
      debtStatus: "มีหนี้สินนอกระบบ",
      risks: {
        academic: true,
        substance: false,
        gaming: true,
        relationship: false,
        financial: true,
        travelRisk: false
      },
      riskNotes: "นักเรียนอาศัยอยู่กับคุณยายที่อายุมาก สภาพบ้านเก่าชำรุดทรุดโทรม หลังคามีรอยรั่วหลายจุด นักเรียนมีพฤติกรรมเล่นเกมดึก ขาดเรียนบ่อยครั้งในวิชาเช้า และผลการเรียนเฉลี่ยลดต่ำลงเหลือ 1.85",
      housePhoto: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&auto=format&fit=crop&q=60",
      parentPhoto: "https://images.unsplash.com/photo-1548142813-c348350df52b?w=600&auto=format&fit=crop&q=60",
      screeningResult: "มีปัญหา",
      counselorNotes: "ประสานงานงานแนะแนวเพื่อช่วยเหลือด้านทุนการศึกษาฉุกเฉิน และส่งครูฝ่ายปกครองช่วยตักเตือนจัดตารางเวลาปรับพฤติกรรมติดเกม ร่วมกับคุณยายอย่างใกล้ชิด",
      submittedBy: "ครูสุพรรณ รัตนมาลา"
    }
  },
  {
    id: "6520201018",
    name: "นายพีระพล พลคง",
    level: "ปวช. 2",
    department: "ช่างยนต์",
    room: "1",
    parentName: "นายพิชัย พลคง",
    parentPhone: "088-999-0000",
    address: "56 ต.ดอนช้าง อ.เมือง จ.ขอนแก่น",
    latitude: 16.3540,
    longitude: 102.7540,
    visitStatus: "ยังไม่ได้เยี่ยม"
  },
  {
    id: "6420501004",
    name: "นางสาวศิริพร บุญรอด",
    level: "ปวช. 3",
    department: "คหกรรมศาสตร์",
    room: "1",
    parentName: "นางสมพร บุญรอด",
    parentPhone: "084-555-1234",
    address: "14/2 หมู่ 8 ต.ท่าพระ อ.เมือง จ.ขอนแก่น",
    latitude: 16.3210,
    longitude: 102.8125,
    visitStatus: "เยี่ยมแล้ว",
    visitData: {
      visitDate: "2026-06-22",
      travelInfo: "รถยนต์ส่วนตัว เข้าซอยถัดจากวัดท่าพระ 200 เมตร",
      latitude: 16.3210,
      longitude: 102.8125,
      houseCondition: "มั่นคงแข็งแรง",
      houseOwnership: "บ้านตนเอง",
      familyStatus: "อยู่กับมารดา (บิดาเสียชีวิต/แยกทาง)",
      relationshipScale: 5,
      averageMonthlyIncome: 15000,
      debtStatus: "ไม่มีหนี้สิน",
      risks: {
        academic: false,
        substance: false,
        gaming: false,
        relationship: false,
        financial: false,
        travelRisk: false
      },
      riskNotes: "มารดาประกอบอาชีพค้าขาย อาหารไทยในตลาดท่าพระ อบรมเลี้ยงดูลูกเป็นอย่างดี นักเรียนมีความประพฤติเรียบร้อย ขยันเรียนและช่วยมารดาทำอาหารขายทุกวันเสาร์-อาทิตย์",
      housePhoto: "https://images.unsplash.com/photo-1464146072230-91cabc968266?w=600&auto=format&fit=crop&q=60",
      parentPhoto: "https://images.unsplash.com/photo-1543269865-cbf427effbad?w=600&auto=format&fit=crop&q=60",
      screeningResult: "ปกติ",
      counselorNotes: "นักเรียนเป็นเด็กดี มีความตั้งใจเรียนสูง ควรผลักดันให้เป็นตัวแทนห้องในกิจกรรมแผนกคหกรรม",
      submittedBy: "ครูอรทัย คหกรรมดี"
    }
  },
  {
    id: "6330901015",
    name: "นายภานุพงศ์ ศรีสุข",
    level: "ปวส. 1",
    department: "คอมพิวเตอร์ธุรกิจ",
    room: "1",
    parentName: "นายประเสริฐ ศรีสุข",
    parentPhone: "087-444-5555",
    address: "200 ถ.รื่นรมย์ อ.เมือง จ.ขอนแก่น",
    latitude: 16.4290,
    longitude: 102.8315,
    visitStatus: "ยังไม่ได้เยี่ยม"
  },
  {
    id: "6520301010",
    name: "นางสาวอรปรียา แสงทอง",
    level: "ปวช. 2",
    department: "การบัญชี",
    room: "1",
    parentName: "นางนวลใจ แสงทอง",
    parentPhone: "089-123-4567",
    address: "444 หมู่ 2 ต.เมืองเก่า อ.เมือง จ.ขอนแก่น",
    latitude: 16.3980,
    longitude: 102.8190,
    visitStatus: "ยังไม่ได้เยี่ยม"
  }
];
